on:
  pull_request:
  push:
    branches:
      - main
    tags-ignore:
      - 'v*'

jobs:
  fmt:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install latest rust
        uses: actions-rs/toolchain@v1
        with:
            profile: minimal
            toolchain: stable
            components: rustfmt
      - name: Check Formatting
        run: |
          cargo fmt --all --check

  test:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - name: Install latest rust
        uses: actions-rs/toolchain@v1
        with:
            toolchain: stable
            profile: minimal
      - uses: taiki-e/install-action@nextest
      - uses: Swatinem/rust-cache@c5ed9ba6b7e1bb8aff90d43acd2f0af4990fa57c
      - uses: taiki-e/install-action@nextest
      - name: Run Tests
        uses: actions-rs/cargo@v1
        with:
          command: nextest
          args: run --all-features --workspace
  